---
layout: resume
title: Scotlyn Davis's Resume
---
# Scotlyn Davis
(480) 645-5474

<div id="webaddress">
<a href="scotlyndavis8@gmail.com">scotlyndavis8@gmail.com</a>
| <a href="http://www.linkedin.com/in/scotlyn-davis">My LinkedIn</a>
</div>


## Education

`2024 - present`
__Brigham Young University—Idaho, Rexburg, ID__

- Bachelor of Science in Accounting
- Data Science Certificate


## Work Experience

`April 2025 - September 2025`

Executive Assistant, *High Caliber Multi-Family*, Surprise, AZ

- Audited capital expenditure budgets for a large multi-family property, identifying variances of over $50,000
- Developed and recorded SOPs for setting up new property businesses in QuickBooks Desktop


`April 2024 - August 2024`

Accounting Intern, *JJ Swart & Co., LLC*, Sun City, AZ

- Performed bookkeeping services as part of a team of five, including entering and reconciling monthly client statements in QuickBooks Desktop
- Ensured proper assembly and filing of more than 100 client folders and corrected 50 instances of missing engagement letters in coordination with coworkers


## Skills
- MS Excel
- Attention to detail
- Organization
- Teamwork
- Communication
- Time management


## Volunteer Experience
`March 2022 - March 2024`

Full-time Volunteer Representative, *The Church of Jesus Christ of Latter-day Saints*, Tampa, FL

- Developed strong social skills and phone etiquette through in-person and phone interactions with 30-50 contacts daily
- Led weekly training meetings in two newly formed volunteer teams over a period of 12 weeks, fostering unity among team members
- Learned new system of volunteer metric reporting and goal setting in six key indicators, leading to a decrease in weekly reporting delays by 50%

`June 2017 - October 2017`

Organizer & Manager, *Eagle Scout Community Service Project*, Goodyear, AZ

- Increased available project preparation time by one week through careful, intentional planning of logistics and written communication with volunteers
- Organized volunteers through effective verbal communication to reduce project execution time by 50%

<!-- ### Footer

Last updated: July 2025 -->